export const AUDIT_ACTIONS = {
  SHIPMENT_STATUS_CHANGED: 'SHIPMENT_STATUS_CHANGED',
  COURIER_ASSIGNED: 'COURIER_ASSIGNED',
  COURIER_REASSIGNED: 'COURIER_REASSIGNED',
  SHIPMENT_CANCELLED: 'SHIPMENT_CANCELLED',
  USER_ROLE_UPDATED: 'USER_ROLE_UPDATED',
  USER_DEACTIVATED: 'USER_DEACTIVATED',
  PAYMENT_REFUNDED: 'PAYMENT_REFUNDED',
  PRICING_RULE_CREATED: 'PRICING_RULE_CREATED',
  PRICING_RULE_UPDATED: 'PRICING_RULE_UPDATED',
  ZONE_CREATED: 'ZONE_CREATED',
  ZONE_DELETED: 'ZONE_DELETED',
  SHIPMENT_DELETED: 'SHIPMENT_DELETED',
  SHIPMENT_UPDATED: 'SHIPMENT_UPDATED'
} as const;

export const AUDIT_ENTITIES = {
  SHIPMENT: 'shipment',
  USER: 'user',
  PAYMENT: 'payment',
  PRICING_RULE: 'pricing_rule',
  ZONE: 'delivery_zone'
} as const;
