export const NOTIFICATION_TYPES = {
  PAYMENT_CONFIRMED: 'PAYMENT_CONFIRMED',
  COURIER_ASSIGNED: 'COURIER_ASSIGNED',
  NEW_ASSIGNMENT: 'NEW_ASSIGNMENT',
  ASSIGNMENT_REMOVED: 'ASSIGNMENT_REMOVED',
  SHIPMENT_UPDATE: 'SHIPMENT_UPDATE',
  DELIVERED: 'DELIVERED',
  DELIVERY_FAILED: 'DELIVERY_FAILED',
  SHIPMENT_CANCELLED: 'SHIPMENT_CANCELLED'
} as const;
