export const SHIPMENT_STATUSES = [
  'PENDING', 'CONFIRMED', 'PICKUP_ASSIGNED', 'PICKED_UP',
  'IN_TRANSIT', 'OUT_FOR_DELIVERY', 'DELIVERED', 'FAILED_DELIVERY',
  'RETURNED', 'CANCELLED'
] as const;

export type ShipmentStatus = (typeof SHIPMENT_STATUSES)[number];
